<?php $version = '4.1 Live MIDI Piano'; ?>
<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Neon Loop Station <?=htmlspecialchars($version)?></title><link rel="stylesheet" href="assets/style.css"></head><body>
<main class="app">
<header class="hero"><div><p class="eyebrow">PHP + Web Audio API + Web MIDI</p><h1>Neon Loop Station <span><?=htmlspecialchars($version)?></span></h1><p>Pady i klawiatura MIDI mają osobne banki brzmień, zapisy presetów, mapowanie klawiszy, edycję sampli, piano view i eksport.</p></div><div class="transport"><button id="bootBtn" class="primary">Uruchom audio</button><button id="playBtn">▶ Play</button><button id="stopBtn">■ Stop</button><button id="recBtn" class="danger">● Nagraj</button><button id="exportBtn">⬇ Export WAV</button></div></header>
<section class="panel master-grid"><label>BPM <input id="bpm" type="number" min="55" max="220" value="120"></label><label>Kroki <select id="steps"><option>16</option><option>32</option></select></label><label>Swing <input id="swing" type="range" min="0" max="0.45" step="0.01" value="0.08"></label><label>Master <input id="masterVol" type="range" min="0" max="1" step="0.01" value="0.85"></label><label>Preset <select id="presetSelect"></select></label><button id="saveProjectBtn">Zapisz projekt</button><button id="loadProjectBtn">Wczytaj projekt</button><button id="clearBtn">Wyczyść</button></section>
<section class="grid two"><div class="panel"><div class="section-head"><h2>Pady i mapowanie</h2><button id="randomKitBtn">Losowy kit</button></div><p class="hint">Kliknij pad, wybierz brzmienie z listy lub nagrany sample. „Ucz klawisz” pozwala przypisać klawisz z klawiatury komputera.</p><div id="pads" class="pads"></div><div class="mini-tools"><button id="saveKitBtn">Zapisz kit/pady</button><button id="loadKitBtn">Wczytaj kit/pady</button><button id="downloadKitBtn">Pobierz kit JSON</button><label class="fileBtn">Import kit JSON<input id="importKit" type="file" accept="application/json"></label></div></div>
<div class="panel"><div class="section-head"><h2>Bank dźwięków</h2><input id="soundSearch" placeholder="szukaj: kick, bass, fx..."></div><div id="soundList" class="sound-list"></div></div></section>
<section class="grid two"><div class="panel"><div class="section-head"><h2>Nagranie / edytor sampla</h2><button id="uploadBtn">Wyślij na serwer</button></div><canvas id="wave" width="780" height="170"></canvas><div class="editor-grid"><label>Start <input id="trimStart" type="range" min="0" max="1" step="0.001" value="0"></label><label>Koniec <input id="trimEnd" type="range" min="0" max="1" step="0.001" value="1"></label><label>Pitch <input id="pitch" type="range" min="0.25" max="3" step="0.01" value="1"></label><label>Gain <input id="sampleGain" type="range" min="0" max="2" step="0.01" value="1"></label><button id="playSampleBtn">Odsłuch</button><button id="reverseBtn">Reverse</button><button id="normalizeBtn">Normalize</button><button id="cropBtn">Przytnij</button><button id="assignSampleBtn">Przypisz do pada</button><button id="chopBtn">Auto-chop 8 padów</button></div></div>
<div class="panel"><div class="section-head"><h2>MIDI keyboard</h2><button id="midiBtn">Połącz MIDI</button></div><p class="hint">Twoja klawiatura ze zdjęcia wygląda jak M-Audio Keystation Mini 32. Po USB powinna działać jako kontroler MIDI. W Chrome/Edge na HTTPS lub localhost użyj „Połącz MIDI”.</p><div class="midi-controls"><label>Tryb MIDI <select id="midiMode"><option value="instrument">Osobny instrument MIDI</option><option value="pads">Nutki C2-D#3 grają pady</option><option value="chromatic">Chromatycznie wybrany pad</option></select></label><label>Brzmienie MIDI <select id="midiInstrument"></select></label><label>Octave <span id="octaveLabel">0</span><div class="octaveBtns"><button id="octDown">−</button><button id="octUp">+</button></div></label><label>MIDI Vol <input id="midiVol" type="range" min="0" max="1.5" step="0.01" value="0.85"></label></div><div class="mini-tools"><button id="saveMidiBtn">Zapisz MIDI preset</button><button id="loadMidiBtn">Wczytaj MIDI preset</button><button id="downloadMidiBtn">Pobierz MIDI JSON</button><label class="fileBtn">Import MIDI JSON<input id="importMidi" type="file" accept="application/json"></label></div><div id="midiStatus" class="midi-status">MIDI: niepołączone</div><div id="piano" class="piano"></div><div class="kbd">Klawiatura komputera: Z S X D C V G B H N J M, Q 2 W 3 E R 5 T 6 Y 7 U</div></div></section>
<section class="panel"><div class="section-head"><h2>Sekwencer</h2><p>Kliknij kratki. Aktywne kroki zagrają przypisane brzmienia padów.</p></div><div id="sequencer" class="sequencer"></div></section>
<section class="grid three"><div class="panel fx"><h2>Filtr</h2><label>Typ <select id="filterType"><option>lowpass</option><option>highpass</option><option>bandpass</option><option>notch</option></select></label><label>Cutoff <input id="cutoff" type="range" min="80" max="16000" value="9000"></label><label>Resonans <input id="resonance" type="range" min="0" max="25" step="0.1" value="1"></label></div><div class="panel fx"><h2>Delay</h2><label>Czas <input id="delayTime" type="range" min="0.03" max="0.75" step="0.01" value="0.25"></label><label>Feedback <input id="feedback" type="range" min="0" max="0.85" step="0.01" value="0.28"></label><label>Mix <input id="delayMix" type="range" min="0" max="0.8" step="0.01" value="0.18"></label></div><div class="panel fx"><h2>Reverb / Drive</h2><label>Space <input id="reverbMix" type="range" min="0" max="0.8" step="0.01" value="0.18"></label><label>Drive <input id="drive" type="range" min="0" max="1" step="0.01" value="0.12"></label><label>Bitcrush <input id="crush" type="range" min="0" max="1" step="0.01" value="0"></label></div></section>
<section class="panel"><div class="section-head"><h2>Warstwy loopera</h2></div><div id="loops" class="loops"></div></section><footer>Status: <span id="status">gotowy</span></footer></main><script src="assets/app.js"></script></body></html>
